name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
        # Windows explicitly excluded until future support is added
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Check code formatting
        run: pnpm exec prettier --check --ignore-path .gitignore .

      - name: Build project
        run: pnpm build

      - name: Verify build output
        run: |
          if [ ! -f "dist/bvm.js" ]; then
            echo "❌ Expected build output dist/bvm.js not found"
            echo "Available files in dist/:"
            ls -la dist/ || echo "dist/ directory not found"
            exit 1
          fi
          echo "✅ Build output verified: bvm.ts → bvm.js"

      - name: Run CLI smoke tests
        run: |
          chmod +x dist/bvm.js

          echo "Testing bvm --help command..."
          node dist/bvm.js --help

          echo "Testing bvm --version command..."
          node dist/bvm.js --version

          echo "Testing error handling with invalid command..."
          if node dist/bvm.js invalid-command-test 2>/dev/null; then
            echo "❌ CLI should return error for invalid commands"
            exit 1
          else
            echo "✅ CLI properly handles invalid commands"
          fi

          echo "✅ All smoke tests completed successfully"
